### ISSUE TITLE
Web push notification for contest clarifications

### ISSUE THREAD

**Issue by cuom1999** [DMOJ/online-judge#1641] opened 2021-04-15 21:21 UTC
Does DMOJ support web push notification when a clarification added during a contest? Something like CF contests with web alerts and notifications.

**Comment by Ninjaclasher** [comment] 2021-04-15 21:23
See #56.

**Comment by cuom1999** [comment] 2021-04-15 21:30
If I read it correctly, the system has not supported live updates yet, hasn't it?

**Comment by Xyene** [comment] 2022-10-31 06:46
Super late reply, but that's right. Closing this as a duplicate of #56 though; patches of course welcome to add live update support :slightly_smiling_face:

**Closed by Xyene** 2022-10-31 06:46 UTC
