### ISSUE TITLE
Problem statement gets cut off on medium sized screens

### ISSUE THREAD

**Issue by TheAvidDev** [DMOJ/online-judge#1443] opened 2020-06-11 16:39 UTC
On my vertical monitor, with a width of around 1080px, the problem page gets cut off as seen in the screenshot below. I don't think this used to happen, so perhaps a recent change did this.

Browser info: `Mozilla Firefox 77.0.1`

![Screenshot_2020-06-11 4Ever - DMOJ Modern Online Judge](https://user-images.githubusercontent.com/52835679/84415242-7c9e6200-abe0-11ea-94a3-1614a7e4b9d4.png)

**Comment by Ninjaclasher** [comment] 2020-06-11 17:04
Is this a duplicate of #1282? If I recall correctly, the issue isn't with the problem statement. The issue is that the comments are nested too deeply, making the problem statement overflow to the right, since they are part of the same container.

**Comment by Ninjaclasher** [comment] 2020-06-11 17:06
It seems that the fix from #1309 only works for one specific screen width.

**Comment by TheAvidDev** [comment] 2020-06-11 17:10
Ah, you are correct on both, this doesn't happen on problems without many nested comments and it looks like #1309 didn't properly fix this.

**Closed** 2020-06-12 01:32 UTC

**Comment by TheAvidDev** [comment] 2020-06-20 15:54
Looks like this still happens on problems with really long code tags like [`csprng`](https://dmoj.ca/problem/csprng).

![screenshot_20200620_115223](https://user-images.githubusercontent.com/52835679/85205920-7600a080-b2ec-11ea-8529-de9e0e803624.png)
