### ISSUE TITLE
Tickets have infinitely expanding `textarea`

### ISSUE THREAD

**Issue by kiritofeng** [DMOJ/online-judge#945] opened 2019-04-04 14:31 UTC
Reproduction Steps:

1. Open a new ticket
2. Type a very long string

Expected Result: The `textarea` will act like a comment's `textarea` and will break the word to fit.

Actual Behaviour:
![image](https://user-images.githubusercontent.com/15059063/55563913-caf2cf80-56c4-11e9-9bfe-b2323cf9fd7b.png)

**Comment by ehhthing** [comment] 2019-04-27 02:04
NB: This issue is caused by the preview expanding, not the text area. In other places (like when creating problems), the preview box expands toward the right of the screen [like this](https://user-images.githubusercontent.com/11021327/56843464-2e5cc100-686f-11e9-8492-43d54f8f2c29.png) so it is not as much of an issue.

**Comment by Xyene** [comment] 2020-03-24 05:00
Fixed in https://github.com/DMOJ/online-judge/pull/1242.

**Closed** 2020-05-06 22:54 UTC
Labels: good first issue, ui, user-tickets
