### ISSUE TITLE
Sync problems to judge server?

### ISSUE THREAD

**Issue by evo-debug** [DMOJ/online-judge#1207] opened 2019-12-08 16:15 UTC
Hi, how do I sync the problems from the site to the judge? I used two different virtual machines for the judge and the site, is there a command to pull the problems?

Or do the judge and site have to be on the same virtual machine?

**Comment by Xyene** [comment] 2019-12-08 17:40
Closing as duplicate of https://github.com/DMOJ/judge-server/issues/592.

**Closed by Xyene** 2019-12-08 17:40 UTC
Labels: duplicate
