### ISSUE TITLE
Select judge to submit on

### ISSUE THREAD

**Issue by Xyene** [DMOJ/online-judge#79] opened 2015-03-27 01:19 UTC
Useful to prevent spam submissions to get the fastest judge. Doesn't impact our performance much, either.

**Comment by quantum5** [comment] 2015-03-27 01:20
Duplicate of #77.

**Comment by Xyene** [comment] 2015-03-27 01:22
Sigh, misleading issue names. My bad. TooManyIssuesException.

**Comment by Xyene** [comment] 2015-03-27 01:30
Wait, on further discussion with @FatalEagle this is *not* a duplicate and the title of #77 is what I thought it was, so not misleading. Reopened.

**Comment by quantum5** [comment] 2015-03-27 01:34
We shouldn't encourage users to religiously select judges as it defeats the purpose of multiple judges.

**Comment by Xyene** [comment] 2015-03-27 01:36
If it's a 3-level deep nested dropdown, it'd be pretty inconvenient to select at all times. Rather, I see people using regular submit until they have an AC solution, then submitting under the fastest judge for ranking. Which in my opinion is more fair since our judges have unequal capacity.

**Comment by FatalEagle** [comment] 2015-03-27 01:37
Maybe require something even more annoying like a codecha to submit on a particular judge.

**Comment by Xyene** [comment] 2015-03-27 01:37
Yea, something annoying like that would prevent abuse.

**Comment by quantum5** [comment] 2015-03-27 01:48
And of course admin exemption from codechas.

I REALLY REALLY HATE IT.

**Comment by FatalEagle** [comment] 2015-03-27 01:50
Another idea: either submit codecha, or do a survey (and make $$$ for us) to submit. http://screencloud.net/v/5rmi

**Comment by quantum5** [comment] 2015-03-27 01:52
Alright as long as we make it hard but not too bad to warrant registering a new account.

**Comment by Xyene** [comment] 2017-04-24 01:24
This'd be really nice for admins, and debugging.

**Comment by Xyene** [comment] 2017-04-24 01:49
![image](https://cloud.githubusercontent.com/assets/1403503/25319727/c567dafa-286e-11e7-9ab1-834b59841d26.png)

**Closed** 2020-04-20 00:10 UTC
Labels: bridge, feature, judging, ui
