### ISSUE TITLE
Show problem link when users try to view submissions to unsolved problems

### ISSUE THREAD

**Issue by Harry7557558** [DMOJ/online-judge#1524] opened 2020-09-04 18:52 UTC
When a regular user (like me) clicks a link to a submission that the problem the user hasn't solved yet, DMOJ shows a blue `unauthorized_access` page, and the user doesn't know which problem he has to solve to view the submission.

Users should be able to see which problem he/she needs to solve to view the submission. DMOJ should tell the user "You must solve problem xxx to view this submission.", instead of giving an error page.

When a user requests a private problem, DMOJ should tell the user "This problem is unavailable", "This problem is private to specific users" or "Only users in the following organizations may access this problem:" (just like that for contests), instead of giving a "No such problem" page.

Although I'm not sure how it works, I think if a user has points earned from private problems, the user's problem solved count in leaderboard/user tables should include these private problems. Other users who have no access to these problems should see an "xxx private problems not shown" in the problem tab of the user's profile, not wondering why the user's point is (sometimes much) higher than what he/she should be.

**Comment by Ninjaclasher** [comment] 2020-09-04 18:55
Duplicate of #894.

**Closed** 2020-09-04 19:01 UTC

**Comment by Xyene** [comment] 2020-09-05 00:14
> Users should be able to see which problem he/she needs to solve to view the submission. DMOJ should tell the user "You must solve problem xxx to view this submission.", instead of giving an error page.

This sounds fine to me (#894 as mentioned), and we'd accept a PR implementing this functionality.

> ... not wondering why the user's point is (sometimes much) higher than what he/she should be.

Private problems should _not_ be counting towards user points. That would be a bug; if you have any instances of that happening on dmoj.ca, please file an issue about it.
